kind = "api"
previewPath = "/api"
title = "FisioBase API"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 5000
name = "API Server"
paths = ["/api"]

[services.development]
run = "python ../../app.py"

[services.production.run]
args = ["gunicorn", "--chdir", "../..", "--bind", "0.0.0.0:5000", "app:app"]

[services.production.run.env]
PORT = "5000"
